// Glossario tecnico di cantiere. Definizioni brevi, senza usare il termine nella definizione,
// con un riferimento concreto al cantiere LA Torriani (E / T / A/B).
export const GLOSSARIO = [
  {
    cat: 'Struttura',
    voci: [
      ['Solaio', 'Il piano orizzontale che separa un livello dall\'altro e regge i carichi di calpestio, trasferendoli a travi e pilastri.', 'In E ogni livello sarà chiuso da uno di questi; il primo è quello di piano terra sopra l\'interrato.'],
      ['Soletta', 'Lastra piana in calcestruzzo armato, gettata in opera, che forma il piano orizzontale portante.', 'Quella di piano terra di E è in armatura, pronta al getto.'],
      ['Impalcato', 'L\'insieme del piano strutturale completo a una data quota, pronto a ricevere il livello superiore.', 'La Torre T ne ha completati 4.'],
      ['Pilastro', 'Elemento verticale portante che raccoglie i carichi dei solai e li scarica alle fondazioni.', 'Quelli del piano terra di E sono già gettati sull\'interrato.'],
      ['Setto portante', 'Parete verticale in cemento armato che porta i carichi e irrigidisce l\'edificio contro le forze orizzontali.', 'Quelli dell\'interrato di E delimitano box e cantine.'],
      ['Nucleo rigido', 'Il vano scala-ascensore in cemento armato che fa da spina di irrigidimento contro sisma e vento.', 'Nella Torre T cresce per primo, in anticipo sui piani.'],
      ['Platea di fondazione', 'Piastra continua in cemento armato che appoggia sul terreno e distribuisce su tutta la superficie il peso dell\'edificio.', 'E poggia su questa soluzione (capitolato).'],
      ['Travi rovesce', 'Travi di fondazione con la parte più alta rivolta in basso, per raccogliere i carichi dei pilastri e ripartirli sul terreno.', 'Alla base dei corpi del complesso.'],
      ['Copriferro', 'Lo spessore di calcestruzzo che ricopre i ferri d\'armatura e li protegge da ruggine e fuoco.', 'Garantito dai distanziatori nelle solette di E.'],
      ['REI 120', 'Classe di resistenza al fuoco: l\'elemento mantiene tenuta e capacità portante per 120 minuti.', 'Requisito tipico di vani scala e box del complesso.'],
    ],
  },
  {
    cat: 'Casseforme e getto',
    voci: [
      ['Cassaforma', 'Lo stampo provvisorio, in legno o metallo, che contiene il calcestruzzo fresco finché non indurisce nella forma voluta.', 'Usata per pilastri, setti e solette di tutti i corpi, E compreso.'],
      ['Pannello iDeck', 'Sistema di casseratura a pannelli per solai, con appoggi rapidi che velocizzano montaggio e smontaggio.', 'Tipico dei solai dei piani correnti (es. Torre T).'],
      ['Puntello telescopico', 'Sostegno metallico regolabile in altezza che regge casseforme e solai finché il getto non porta da solo.', 'Fitti sotto le solette appena gettate di E.'],
      ['Testa drophead', 'Testa speciale del puntello che permette di togliere i pannelli lasciando il solaio ancora sostenuto.', 'Consente di riusare le casseforme più in fretta, piano su piano.'],
      ['Rete elettrosaldata', 'Griglia di tondini d\'acciaio saldati, posata nelle solette per armarle e distribuire le tensioni.', 'Visibile nella soletta di piano terra di E prima del getto.'],
      ['Distanziatore', 'Piccolo supporto che tiene i ferri sollevati dal fondo della cassaforma, garantendo il copriferro.', 'Sotto l\'armatura della soletta di E.'],
      ['Getto', 'La colata del calcestruzzo fresco dentro le casseforme.', 'Quello della soletta di piano terra di E è imminente.'],
      ['Maturazione', 'Il periodo in cui il calcestruzzo indurisce e sviluppa resistenza dopo la colata; richiede tempo e umidità.', 'Dopo ogni colata in E si attende prima di caricare la struttura.'],
      ['Disarmo', 'La rimozione delle casseforme quando il calcestruzzo ha fatto presa a sufficienza.', 'Dopo quello della soletta di E si potrà elevare il piano terra.'],
      ['Slump', 'Misura della fluidità del calcestruzzo fresco: quanto si abbassa un cono di prova appena tolto lo stampo.', 'Controllato ai getti importanti come le solette di E.'],
      ['Ago vibrante', 'Attrezzo che si immerge nel calcestruzzo fresco per far uscire l\'aria e compattarlo attorno ai ferri.', 'Usato durante le colate di solette e setti.'],
      ['Disarmante', 'Prodotto steso sulle casseforme perché il calcestruzzo non vi aderisca e la superficie resti liscia.', 'Applicato prima di ogni colata.'],
      ['Table formwork', 'Grandi tavoli di cassaforma per solai, spostati interi da una posizione all\'altra con la gru.', 'Velocizzano i piani ripetuti della Torre T.'],
      ['Flying formwork', 'Casseforme per solai spostate con la gru da un piano al successivo senza smontarle.', 'Tecnica utile sui corpi alti come T.'],
    ],
  },
  {
    cat: 'Impermeabilizzazione e isolamento',
    voci: [
      ['Guaina bituminosa', 'Manto impermeabile in rotoli, steso a caldo, che protegge dall\'acqua coperture e parti interrate.', 'Prevista su coperture e sull\'interrato di E.'],
      ['Telo bugnato antistrappo', 'Membrana plastica a rilievi che crea un\'intercapedine drenante contro i muri controterra.', 'A protezione dei setti interrati di E.'],
      ['Cappotto termico', 'Strato isolante applicato all\'esterno delle murature per ridurre le dispersioni di calore.', 'Previsto sulle murature perimetrali di E (capitolato).'],
      ['Ponte termico', 'Punto della costruzione dove il calore fugge più facilmente, per interruzione dell\'isolante o materiali diversi.', 'Il cappotto continuo di E serve a limitarli.'],
      ['Poroton', 'Blocco in laterizio alveolato per murature, con buone doti di isolamento e inerzia termica.', 'Le pareti perimetrali di E sono in questo laterizio più cappotto.'],
      ['Strato drenante', 'Livello di ghiaia o materiale poroso che allontana l\'acqua dalle strutture interrate.', 'Attorno alle fondazioni dei corpi del complesso.'],
      ['Vespaio', 'Intercapedine ventilata sotto il piano terra, spesso con elementi a cupola, che isola dall\'umidità del terreno.', 'Predisposto sotto il piano terra di E.'],
    ],
  },
  {
    cat: 'Impianti',
    voci: [
      ['PE-Xa', 'Tubo in polietilene reticolato ad alta densità, flessibile e resistente, usato per il riscaldamento a pavimento.', 'Sarà annegato nei massetti di E per il radiante (capitolato).'],
      ['Pompa di calore aria-acqua', 'Macchina che estrae calore dall\'aria esterna per scaldare l\'acqua degli impianti, con alta efficienza.', 'Centralizzata per E, con contabilizzatore dedicato.'],
      ['VMC', 'Ventilazione meccanica controllata: ricambia l\'aria degli ambienti in modo continuo e filtrato, senza aprire le finestre.', 'Prevista in E, con recupero di calore.'],
      ['Recuperatore di calore', 'Scambiatore che riscalda l\'aria pulita in ingresso usando il calore di quella viziata in uscita.', 'È il cuore della VMC di E.'],
      ['Collettore radiante', 'Armadietto da cui partono e tornano i circuiti dei tubi del pavimento, regolando ogni zona.', 'Distribuirà il PE-Xa nelle stanze di E.'],
      ['Cavidotto', 'Tubo corrugato posato nelle strutture in cui far scorrere i cavi elettrici o dati.', 'Annegati nelle solette e nei muri di E.'],
      ['Bocca di lupo', 'Apertura protetta a livello del terreno che porta aria e luce ai locali interrati.', 'Rimossa da E su tua richiesta — da definire la ventilazione alternativa del box.'],
      ['Drophead', 'Non è un impianto: è la testa speciale dei puntelli delle casseforme (vedi "Testa drophead").', 'Accessorio di cantiere per il disarmo rapido dei solai.'],
    ],
  },
  {
    cat: 'Fasi di cantiere',
    voci: [
      ['Grezzo', 'L\'edificio completo di strutture e murature ma senza intonaci, impianti finiti e finiture.', 'A/B sono al grezzo avanzato; E è ancora alle strutture.'],
      ['Elevazione', 'La fase in cui si costruiscono i piani fuori terra, uno sopra l\'altro.', 'T è in questa fase; E la inizierà dopo la soletta di piano terra.'],
      ['Tamponamento', 'Le pareti esterne non portanti che chiudono lo scheletro strutturale.', 'In corso su A/B, non ancora su E.'],
      ['Frontalino', 'La fascia in cemento del bordo di balcone o solaio, qui a profilo curvo.', 'I profili ondulati caratterizzano A/B e C.'],
      ['Piano fuori terra', 'Ogni livello abitabile sopra il livello del suolo.', 'E ne ha 0: è ancora a quota interrato.'],
      ['Piano interrato', 'Il livello sotto il suolo, per box, cantine e locali tecnici.', 'Quello di E è completato.'],
      ['Quota di gronda', 'L\'altezza del bordo superiore della facciata, dove finisce la parte in elevazione.', 'B l\'ha raggiunta (5/5).'],
      ['Puntellamento', 'L\'insieme dei sostegni provvisori che reggono solai e strutture fresche finché non portano da soli.', 'Sotto le solette recenti di E e T.'],
    ],
  },
]
